In [1]:
import numpy as np

In [2]:
Tab = np.arange(1,10)
Tab = Tab[::-1]
Tab = Tab.reshape(3,3)
print(Tab)

Tab = np.arange(9,0,-1).reshape(3,3)
print(Tab)

[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [9]:
Tab[:,0].reshape(3,1)

array([[9],
       [6],
       [3]])

In [11]:
Tab[:,1:]

array([[8, 7],
       [5, 4],
       [2, 1]])

In [6]:
Tab[:-1,:-1]

Tab[:2,:2]

array([[9, 8],
       [6, 5]])

In [6]:
Tab[:,0]

array([9, 6, 3])

In [13]:
Tab[::-1,:]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])