# 100 Numpy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import random as rd

#### 2. Print the numpy version and the configuration (★☆☆)

'1.24.3'

#### 3. Create a null vector of size 10 (★☆☆)

 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

[[[7072 1528 6209]
  [4437 5882 7153]
  [8007 7417 2099]]

 [[8922 3115 6946]
  [5269 9866 6934]
  [7353 2229 4311]]

 [[ 962 9209 4804]
  [9353 3607 1387]
  [7218  985 9331]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

[[4184 7876 2246 9525 1297  738 4713 3207 2900 4141]
 [9074 8241 3655 7801 9610 9738 3318 1124 5244 8297]
 [7360 8293  190 6705 2779 1301 5084 2835 3477 5845]
 [5616 8744 7627 1240 6406 2494 6475 5402 3590 2715]
 [6139 8812 2496 9065 5234 3182 6405 8073 3877 2473]
 [7310 5856 8850 1650 5383 6834 8411 6067 3914 1973]
 [ 537 1761 2418 5434 9865 4879 3365 1739 5195 2178]
 [5562 7703 8166 5170 3790 8824 1715 2268 2977 6227]
 [8050 8570  535 9087 5916 5080 4327 2359 7794 8059]
 [2790 9653 1073 6781 8251  845 9110 8321 6361 7365]]
9865 190


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

 [7800 5059 7425  771 7236 1534 9883 6025 2949 5726 3474 2968 4407 5857
 6620 9822  308 8720 3965 3131 9421 2995 4487  443 7639 4856 2225 4325
 8829 6895] 
 5193.166666666667


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1.])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

[[ 4 11 19  8 22]
 [16  0  5  6 17]
 [14 18  2 10 23]
 [21  7  9 12 20]
 [ 3 13  1 15 24]]
[[-0.83333333 -0.54166667 -0.20833333 -0.66666667 -0.08333333]
 [-0.33333333 -1.         -0.79166667 -0.75       -0.29166667]
 [-0.41666667 -0.25       -0.91666667 -0.58333333 -0.04166667]
 [-0.125      -0.70833333 -0.625      -0.5        -0.16666667]
 [-0.875      -0.45833333 -0.95833333 -0.375       0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

[[77 96 62]
 [21 11 35]
 [ 3 10  4]
 [47 23 49]
 [76 14 98]] 
 [[60 67]
 [47 82]
 [12 17]]
[[ 9876 14085]
 [ 2197  2904]
 [  698  1089]
 [ 4489  5868]
 [ 6394  7906]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

[ 1 12 16 10  6 13  9  5 15  2  4 21  0  3 24]
[ 1 12 16 10 -6 13  9 -5 15  2 -4 21  0  3 24]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

[ 6.  4. -6.  3. -5. -1.  4. -1. -6. 10.]


#### 30. How to find common values between two arrays? (★☆☆)

 [1 0 3 0 4 8 0 8 0 7] 
 [4 0 7 6 0 3 1 4 3 6] 
 [0 1 3 4 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

[3. 8. 3. 5. 9. 8. 5. 1. 2. 3.]
[3. 8. 3. 5. 9. 8. 5. 1. 2. 3.]
[3. 8. 3. 5. 9. 8. 5. 1. 2. 3.]
[3 8 3 5 9 8 5 1 2 3]
[3. 8. 3. 5. 9. 8. 5. 1. 2. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

array([[7, 1, 9, 3, 5],
       [8, 0, 6, 2, 4]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

array([0.09592688, 0.89669211, 0.72356018, 0.48341283, 0.52889142,
       0.36211308, 0.64894049, 0.17455055, 0.35694373, 0.73455043])

#### 40. Create a random vector of size 10 and sort it (★★☆)

[0.17920713 0.22616402 0.23678839 0.41226913 0.47144338 0.50984683
 0.78329416 0.79360471 0.80253454 0.89205529]


#### 41. How to sum a small array faster than np.sum? (★★☆)

 15 
 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

 [8 3 2 1 3 2 8 2 2 7] 
 [8 4 0 6 4 2 3 2 4 4] 
 [ True False False False False  True False  True False False]
 False


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

 [[35.05307582  7.69341842]
 [39.38704458  8.85338255]
 [83.99575655 83.96254706]
 [80.41497329 36.01006   ]
 [21.52812629 43.2652467 ]
 [20.72412975 42.49459115]
 [99.71328038 14.08935035]
 [79.23075411 50.4530425 ]
 [45.44082972 60.97740719]
 [32.21152378 82.38896246]] 
 [[ 35.88741857  12.37894925]
 [ 40.36981129  12.66833354]
 [118.76445776  44.98867122]
 [ 88.10954745  24.12297463]
 [ 48.32537422  63.54576336]
 [ 47.27874608  64.00203379]
 [100.70376397   8.04257329]
 [ 93.93094216  32.48841732]
 [ 76.04678293  53.30623944]
 [ 88.46198844  68.64604619]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

[14 47 18 42 23 38 16 43 13 25] 47
[14  0 18 42 23 38 16 43 13 25]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 
 10.406700173101758 
 10


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

[[0.         0.6241489  0.75679156 0.56652647 0.89268865 0.84189268
  0.90457842 0.39863162 0.84278847 0.55353423]
 [0.6241489  0.         0.59921305 0.66515968 0.28539955 0.54633145
  0.35765051 0.72854365 0.33348311 0.77069095]
 [0.75679156 0.59921305 0.         0.27472385 0.80524349 0.16165298
  0.92883393 1.08719069 0.92370317 0.40305748]
 [0.56652647 0.66515968 0.27472385 0.         0.92658893 0.42657156
  1.02213442 0.94417625 0.99660236 0.13505651]
 [0.89268865 0.28539955 0.80524349 0.92658893 0.         0.70513538
  0.15031578 0.91586816 0.19636722 1.04159307]
 [0.84189268 0.54633145 0.16165298 0.42657156 0.70513538 0.
  0.84085609 1.13341051 0.84784006 0.55905873]
 [0.90457842 0.35765051 0.92883393 1.02213442 0.15031578 0.84085609
  0.         0.86143114 0.07691009 1.12813063]
 [0.39863162 0.72854365 1.08719069 0.94417625 0.91586816 1.13341051
  0.86143114 0.         0.78558894 0.94825789]
 [0.84278847 0.33348311 0.92370317 0.99660236 0.19636722 0.84784006
  0.07691009 0.78558

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 2. 0. 0. 0. 0. 8. 9.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [6. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [7. 0. 0. 0. 0. 0. 8. 0. 0. 0.]
 [0. 0. 0. 0. 6. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

[[ 0.07013907 -0.13747783  0.12505872 -0.11387085  0.05615088]
 [-0.10162412  0.42742024  0.489911   -0.42291849 -0.39278863]
 [ 0.19813926 -0.148015   -0.15991443  0.00555585  0.10423431]
 [-0.02638298  0.451231   -0.4644748   0.45941749 -0.41979072]
 [ 0.2794598   0.26617523 -0.22928228 -0.42674776  0.11039501]]


#### 59. How to sort an array by the nth column? (★★☆)

[[4 8 2]
 [3 1 1]
 [0 1 7]]
[[3 1 1]
 [0 1 7]
 [4 8 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

[[1 2 0 1 2 1 2 1 1 2]
 [2 0 0 1 1 0 1 0 2 2]
 [0 2 1 1 1 1 2 1 0 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

 [0.78954004 0.27723624 0.07821187 0.41350002 0.87067901 0.10515828
 0.85839688 0.09180741 0.85287204 0.43266663] 
 0.5 
 0.43266662977020864


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

[5. 4. 3. 2. 4. 3. 4. 2. 1. 2.]
[9. 7. 5. 3. 7. 5. 7. 3. 1. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

[[60 56 55 52]
 [54 48 58 51]
 [35 41 53 49]]
[[60 56 55 52]
 [54 48 58 51]
 [35 41 53 49]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

[0.52826168 0.58722721 0.54099166 0.56844813 0.4886342  0.59670499
 0.52878345 0.60871236 0.66610987 0.51526619]
0    0.528262
1    0.587227
2    0.540992
3    0.568448
4    0.488634
5    0.596705
6    0.528783
7    0.608712
8    0.666110
9    0.515266
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

array([1.40272213, 1.61864984, 0.81095616, 1.34286717, 1.58987142])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

[( 1,  7) ( 1, 67) ( 3, 30) ( 3, 60) ( 4, 23) ( 4, 66) ( 5, 26) ( 5, 62)
 ( 7, 22) ( 7, 58) ( 7, 67) ( 8, 43) ( 8, 69) (15, 76) (15, 84) (20, 80)
 (20, 93) (22, 58) (23, 50) (23, 60) (23, 66) (26, 62) (30, 60) (35, 43)
 (35, 64) (43, 64) (43, 69) (50, 60) (76, 84) (80, 93)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

array([ 0.08444359,  0.42111982, -0.38092701,  0.53732857,  0.41094496,
        0.26823632,  0.02855311, -0.13194226, -0.1416815 , -0.90920231,
        0.15395755, -0.36271551,  0.7018996 , -0.66073894,  0.67283368,
       -0.48221516, -0.20642066,  0.04175243, -0.83385807, -0.35665424,
       -0.75173831,  0.46884532, -0.9249826 , -0.9679075 ,  0.86940373,
        0.47101037, -0.71441956, -0.78542902,  0.6528735 , -0.76035729,
        0.92895384,  0.12097142,  0.92603281, -0.37097632,  0.93495474,
       -0.4981282 , -0.54530853, -0.89285695, -0.32756654,  0.45699473,
       -0.03320808, -0.42857442, -0.82913562,  0.90390034, -0.93374551,
        0.59973603,  0.5927959 , -0.17871031, -0.56333402,  0.12142082,
        0.26883294, -0.33601153, -0.7112892 , -0.79469897,  0.28132426,
       -0.1124218 , -0.29134888, -0.22678603,  0.23334396,  0.31180105,
        0.73242107, -0.88273135,  0.52745678,  0.84856394,  0.34159664,
        0.08487413,  0.59166545, -0.49483654, -0.50361257,  0.17

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

[ 9.21883624  2.6656336  12.9065758   7.188759    5.61662111  0.01746569
 12.64584903  1.06960022 13.74544075  0.7018938 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

[[ 0.4705305  17.25782302 11.93669228  8.49384812  6.39839723  6.73248186
  16.9503688   1.05490049  3.68833882 14.66656756]
 [ 3.54209281  8.06533248  4.09165652  0.34213577  0.04260234  3.00488846
   8.04507437  5.05967897  5.40596562  5.75987786]
 [13.97444326 11.91370953  3.55183795  6.9024385   9.08485012  7.53000026
  12.53268673  4.68011792 11.06328786  0.27170172]
 [ 3.67084043  3.52456292  8.51233881  4.40595513  5.68727011 10.34587211
   3.0696166  13.15912508  2.71315244  8.76985829]
 [ 5.27278726 16.22503157  6.2803444   2.92125499  0.5454408   1.02852314
  16.28169785  2.01842292  1.469025    9.40106896]
 [ 6.47360943  1.99077989  1.3450109   5.29093684  4.57019998  0.26211237
   2.17785677  7.51976672 11.63435756  0.35136891]
 [11.18903086  6.922894    3.33255146  6.96052622  7.77092238  4.59671863
   7.38654307  0.79872687 12.12191218  1.10727305]
 [12.54602058 18.33733581  0.68915341  2.4164206   5.91708559  6.29884726
  18.84187442  8.39434462  5.78314934  4.84374975]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

10


#### 83. How to find the most frequent value in an array?

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

[[[[3 2 0]
   [4 2 2]
   [4 0 4]]

  [[2 0 1]
   [2 2 0]
   [0 4 0]]

  [[0 1 2]
   [2 0 1]
   [4 0 2]]

  [[1 2 3]
   [0 1 4]
   [0 2 1]]

  [[2 3 4]
   [1 4 2]
   [2 1 1]]

  [[3 4 2]
   [4 2 0]
   [1 1 2]]

  [[4 2 0]
   [2 0 1]
   [1 2 4]]

  [[2 0 4]
   [0 1 3]
   [2 4 4]]]


 [[[4 2 2]
   [4 0 4]
   [4 2 3]]

  [[2 2 0]
   [0 4 0]
   [2 3 2]]

  [[2 0 1]
   [4 0 2]
   [3 2 1]]

  [[0 1 4]
   [0 2 1]
   [2 1 0]]

  [[1 4 2]
   [2 1 1]
   [1 0 3]]

  [[4 2 0]
   [1 1 2]
   [0 3 3]]

  [[2 0 1]
   [1 2 4]
   [3 3 4]]

  [[0 1 3]
   [2 4 4]
   [3 4 1]]]


 [[[4 0 4]
   [4 2 3]
   [0 2 4]]

  [[0 4 0]
   [2 3 2]
   [2 4 3]]

  [[4 0 2]
   [3 2 1]
   [4 3 3]]

  [[0 2 1]
   [2 1 0]
   [3 3 2]]

  [[2 1 1]
   [1 0 3]
   [3 2 1]]

  [[1 1 2]
   [0 3 3]
   [2 1 1]]

  [[1 2 4]
   [3 3 4]
   [1 1 3]]

  [[2 4 4]
   [3 4 1]
   [1 3 3]]]


 [[[4 2 3]
   [0 2 4]
   [2 4 0]]

  [[2 3 2]
   [2 4 3]
   [4 0 0]]

  [[3 2 1]
   [4 3 3]
   [0 0 0]]

  [[2 1 0]
   [3 3 2]
   [0 0 2]]

  [[1 0 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

[[ 3  8 10  8 13]
 [ 8  8  9  8 11]
 [10  9  8 42  7]
 [ 8  8 42  1 15]
 [13 11  7 15  6]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

[9995 9996 9997 9998 9999]
[9997 9998 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

[0 2 3 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

[[0 1 1]
 [4 0 4]
 [1 3 1]
 [1 2 3]
 [4 4 3]
 [3 1 1]
 [2 1 2]
 [1 0 2]
 [4 3 3]
 [2 1 0]]
[[0 1 1]
 [4 0 4]
 [1 3 1]
 [1 2 3]
 [4 4 3]
 [3 1 1]
 [2 1 2]
 [1 0 2]
 [4 3 3]
 [2 1 0]]
[[0 1 1]
 [4 0 4]
 [1 3 1]
 [1 2 3]
 [4 4 3]
 [3 1 1]
 [2 1 2]
 [1 0 2]
 [4 3 3]
 [2 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

[[0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

array([[0.28530829, 0.10018953, 0.30970448, 0.03749886, 0.45065953,
        0.07116235, 0.37818882, 0.03224336, 0.52379414, 0.23213955],
       [0.29519783, 0.10366236, 0.32043966, 0.03879867, 0.46628058,
        0.07362902, 0.39129785, 0.033361  , 0.54195023, 0.24018613],
       [0.09634358, 0.03383224, 0.10458175, 0.0126627 , 0.15217978,
        0.02403027, 0.1277077 , 0.01088801, 0.17687606, 0.07838944],
       [0.0481292 , 0.01690116, 0.05224464, 0.00632575, 0.07602262,
        0.01200451, 0.0637974 , 0.00543919, 0.08835984, 0.03916007],
       [0.43174451, 0.15161241, 0.4686622 , 0.05674538, 0.68196328,
        0.10768686, 0.57229654, 0.04879246, 0.79263469, 0.3512866 ],
       [0.19840941, 0.06967391, 0.21537504, 0.0260775 , 0.31339815,
        0.0494878 , 0.26300049, 0.02242271, 0.36425751, 0.16143475],
       [0.11369497, 0.03992539, 0.12341682, 0.01494325, 0.17958722,
        0.0283581 , 0.15070774, 0.01284893, 0.20873127, 0.0925073 ],
       [0.00718236, 0.00252217, 0.0077965

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

[-0.21466603  0.19081233]
